apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.7.1
  values:
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
      podAnnotations:
        prometheus.io.scrape: 'true'
        prometheus.io.port: '10254'
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
          service.beta.kubernetes.io/aws-load-balancer-type: external
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-scheme: 'internet-facing'
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 50
        targetCPUUtilizationPercentage: 70
        targetMemoryUtilizationPercentage: 98
  interval: 5m
  dependsOn:
    - name: aws-load-balancer-controller
    - name: kube-prometheus-stack
  install:
    remediation:
      retries: 3
