apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  releaseName: kyverno
  targetNamespace: kyverno
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: kyverno
      version: v2.3.3
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  # https://github.com/kyverno/kyverno/blob/main/charts/kyverno/values.yaml
  values:
    # baseline / restricted / privileged / custom: https://kyverno.io/policies/pod-security/
    podSecurityStandard: disabled
    serviceMonitor:
      enabled: true
    replicaCount: 2
    networkPolicy:
      enabled: true
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  dependsOn:
    - name: kube-prometheus-stack