apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: patch-ingress-nginx.yaml
    target:
      name: ingress-nginx
      kind: HelmRelease
  - path: patch-flagger.yaml
    target: 
      name: flagger
      kind: HelmRelease