apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  releaseName: kube-prometheus-stack
  serviceAccountName: helm-controller
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 20.0.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 1m
