apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  releaseName: aws-load-balancer-controller
  serviceAccountName: helm-controller
  targetNamespace: kube-system
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
  interval: 2m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # values replaced with values on ConfigMap external-config-data
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${awsLoadBalancerControllerIamRoleArn}
    clusterName: ${clusterName}