# Calico is installed as a separate kustomization as Kustomize fails to install due to the Calico operator not ready when the Installation CR is created
# https://github.com/kubernetes-sigs/kustomize/issues/3794#issuecomment-818797622
# This creates two separate GitRepositories: one for the Calico CRDs and operators, and the other for the Calico Installation so we can then create two separate Kustomizations
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: aws-vpc-cni-calico-operator
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/aws/amazon-vpc-cni-k8s
  ignore: |
    # exclude all
    /*
    #include calico operator manifest
    !/config/master/calico-operator.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: aws-vpc-cni-calico-installation
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/aws/amazon-vpc-cni-k8s
  ignore: |
    # exclude all
    /*
    #include calico installation manifest
    !/config/master/calico-crs.yaml