---
# Calico is installed with two separate kustomizations: one for the CRDs and Operator, and the other for the installation as Kustomize fails to install due to the Calico 
# operator not ready when the Installation CR is created
# https://github.com/kubernetes-sigs/kustomize/issues/3794#issuecomment-818797622
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: calico-installation
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: calico-operator
  interval: 1m
  path: "./config/master"
  prune: true
  sourceRef:
    kind: GitRepository
    name: aws-vpc-cni-calico-installation
  wait: true
  timeout: 1m
