apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: calico-operator
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  path: "./config/master"
  prune: true
  sourceRef:
    kind: GitRepository
    name: aws-vpc-cni-calico-operator
  wait: true
  timeout: 1m
