apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      version: 5.0.0
  values:
    # Service should be disabled when using Flagger
    service:
      enabled: false
    ingress:
      enabled: true
      className: nginx
    hpa: 
      enabled: true
  interval: 5m
  dependsOn:
    - name: ingress-nginx
      namespace: ingress-nginx
  install:
    remediation:
      retries: 3